title: generic-python-animated-graph
hero_image: images/banner.png
description: generic-python-animated-graph description
version: 4
listed: false
copyedit: false
last_tested: "2020-01-27"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
